language: python
python:
    - 3.6
before_install:
    - travis_wait travis_retry pip install torch
    - travis_wait travis_retry pip install torchvision
    - travis_wait travis_retry pip install tensorflow
    - travis_wait travis_retry pip install scipy
    - travis_wait travis_retry pip install foolbox==1.3.2
    - travis_wait travis_retry pip install keras
    - travis_wait travis_retry pip install cleverhans
install:
    - pip install -e .
script:
    - pytest